"""Generated by tools/gen_commons_assets.py - do not edit.

SKIN / EYES        how many variants those sheets hold (the option IS
                   the colour, so they need no table).
HAIR / FACE /      [(label, shades), ...] with index 0 always the empty
HEAD / OUTFIT      'None' option, which has no sheet on disk.
ROOM               [(label, wall rgb, floor rgb), ...]
FIGURE             the size every layer is cropped to.
NAMES              the pool the three residents are named from.
"""

SKIN = 9

EYES = 7

HAIR = [
    ('None', 0),
    ('Crop', 7),
    ('Side Part', 7),
    ('Tuft', 7),
    ('Bob', 7),
    ('Spikes', 7),
    ('Buzz', 7),
    ('Curls', 7),
    ('Pompadour', 7),
    ('Long', 7),
    ('Mop', 7),
    ('Cowlick', 7),
    ('Short', 7),
    ('Messy', 7),
    ('Bowl', 7),
    ('Long Bob', 7),
    ('Flat Top', 7),
    ('Swept', 7),
    ('Fringe', 7),
    ('Wavy', 7),
    ('Parted', 7),
    ('Tufts', 7),
    ('Layers', 7),
    ('Shag', 7),
    ('Bouffant', 7),
    ('Swoop', 7),
    ('Quiff', 7),
    ('Straight', 6),
    ('Cat Ears', 6),
    ('Pixie', 6),
]

FACE = [
    ('None', 0),
    ('Glasses', 6),
    ('Monocle', 3),
    ('Mask', 5),
    ('Moustache', 5),
    ('Beard', 5),
]

HEAD = [
    ('None', 0),
    ('Snapback', 6),
    ('Dino Cap', 3),
    ('Beanie', 5),
    ('Police Hat', 6),
    ('Detective', 3),
    ('Balaclava', 3),
    ('Party Hat', 4),
    ('Antennae', 4),
    ('Bolts', 3),
    ('Brain', 3),
    ('Bee', 3),
    ('Chef', 3),
]

OUTFIT = [
    ('None', 0),
    ('Sweater', 10),
    ('Red Jacket', 4),
    ('Blazer', 4),
    ('Stripes', 3),
    ('Suit', 5),
    ('Red Tie', 4),
    ('Varsity', 4),
    ('White Suit', 3),
    ('Chef Coat', 3),
    ('Anorak', 5),
    ('Cardigan', 4),
    ('Office', 3),
    ('Apron', 4),
    ('Vest', 5),
    ('Gi', 3),
    ('Yellow Tee', 3),
    ('Polo', 3),
    ('Flannel', 4),
    ('Overalls', 4),
    ('Tracksuit', 3),
    ('Grey Suit', 4),
    ('Work Coat', 4),
    ('Trench', 4),
    ('Hawaiian', 4),
    ('Blue Shirt', 5),
    ('Dungarees', 3),
    ('Overcoat', 3),
    ('Sailor', 4),
    ('Denim', 4),
    ('Ninja', 3),
    ('Shorts', 5),
    ('Swimwear', 5),
    ('Dress', 3),
]

ROOM = [
    ('Studio', (204, 204, 204), (208, 190, 156)),
    ('Parlour', (177, 88, 85), (103, 52, 46)),
    ('Workshop', (148, 112, 82), (108, 77, 35)),
    ('Clinic', (217, 220, 226), (97, 103, 109)),
    ('Garden', (156, 169, 158), (238, 229, 218)),
    ('Arcade', (129, 133, 193), (133, 133, 132)),
]

FIGURE = (16, 32)

NAMES = [
    'MAE',
    'OSK',
    'REN',
    'IVO',
    'TAL',
    'JUN',
    'KIT',
    'NIX',
    'PIP',
    'ODA',
    'LUM',
    'ZAI',
    'BODE',
    'WREN',
    'ARLO',
    'VESA',
]
