"""Star Grid puzzles, baked by tools/gen_star_grid_puzzles.py.

Each is (label, n, k, rows): an n x n grid whose rows name the
region of every cell with a letter; k stars go in each row,
column and region.  Do not edit - rerun the generator.
"""

PUZZLES = (
    ('SMALL', 6, 1,
     ('FFEEEC',
      'FFFECC',
      'FDDCCC',
      'FAACCC',
      'AACCCB',
      'AACCCB')),
    ('SMALL', 6, 1,
     ('BEAAAC',
      'BEAAAC',
      'BEEEDC',
      'BEEDDD',
      'BBBBFD',
      'BBBBFD')),
    ('SMALL', 6, 1,
     ('DDDDBB',
      'DDDDFB',
      'DDDFFB',
      'AAAFFF',
      'EEACCF',
      'CCCCCC')),
    ('SMALL', 6, 1,
     ('AADDCD',
      'FADDDD',
      'FFFDDD',
      'FFDDDD',
      'BFFEEE',
      'BBBEEE')),
    ('SMALL', 6, 1,
     ('BBBBFF',
      'BBCBFC',
      'DBCCCC',
      'DBECCC',
      'DEEEEC',
      'AAEEEC')),
    ('SMALL', 6, 1,
     ('FFFAAA',
      'DFFABB',
      'DFEABB',
      'DDEEEE',
      'DDEEEC',
      'DDDEEE')),
    ('MEDIUM', 8, 1,
     ('BBCCCCAA',
      'BBBCCCAA',
      'BBBHAAAA',
      'BBBHAAAA',
      'FFBHHHGD',
      'FFFFHDDD',
      'FFFEEDDD',
      'FFFFEEEE')),
    ('MEDIUM', 8, 1,
     ('CCAABGGG',
      'CBBBBGGH',
      'CDBBBGHH',
      'DDDBGGHH',
      'DDDGGGHH',
      'DDGGGGGH',
      'DDFGGGGE',
      'DDDGGGGE')),
    ('MEDIUM', 8, 1,
     ('DDFFFCEE',
      'DFFFFCEE',
      'HHHHFCEB',
      'HHHCCCBB',
      'BBHHBBBB',
      'BBBBBBBB',
      'GBGBBBBB',
      'GGGGBBAA')),
    ('MEDIUM', 8, 1,
     ('CCDDDDDG',
      'CDDDDDDG',
      'CCCFEGGG',
      'FFFFEGAA',
      'FFFFEEEA',
      'HHFFFAAA',
      'HHHAAAAA',
      'BBHHAAAA')),
    ('MEDIUM', 8, 1,
     ('BBBCAAAD',
      'BBBCACAA',
      'HBCCCCCC',
      'HBCCCFFF',
      'HHHHCCFF',
      'HHHEGCGG',
      'HHEEGGGG',
      'HGGGGGGG')),
    ('MEDIUM', 8, 1,
     ('GGGGFFCC',
      'GGGGFFFD',
      'AGGFFFDD',
      'HHBFFFDD',
      'HHBBDFDD',
      'HHHBDDDD',
      'BBHBBDDD',
      'BBBBDDED')),
    ('LARGE', 8, 2,
     ('AAAEEHHC',
      'AAAEEHHC',
      'AAAEEHCC',
      'AABEEHHC',
      'BBBBDFFC',
      'GGGDDFFF',
      'GGGDDFFF',
      'GGGGDFFF')),
    ('LARGE', 8, 2,
     ('DDBBBFFF',
      'DDBBFFFF',
      'DDDBGFGF',
      'DDHGGGGG',
      'EHHAAGCC',
      'EHHHAACC',
      'EHHHAACC',
      'EAAAAACC')),
    ('LARGE', 8, 2,
     ('HHHGGGGG',
      'HHHGGGGG',
      'DHBBBBBG',
      'DDDDEBBF',
      'AAAAEFFF',
      'AAAAEEEE',
      'AAACEEEE',
      'CCCCCEEE')),
    ('LARGE', 8, 2,
     ('GGGAAAFF',
      'GGGAAAFF',
      'GGCCAAFF',
      'CCCCCAFF',
      'ECCCCDBB',
      'EEEEEDBB',
      'HHHHHDBB',
      'HHHHHBBB')),
    ('LARGE', 8, 2,
     ('BBBBEECC',
      'BBBEEECC',
      'BBBEECCC',
      'HHHHEAAC',
      'DDDDAAAA',
      'DDDGGFFA',
      'DDDGGFFF',
      'DDDGGGFF')),
    ('LARGE', 8, 2,
     ('DDBHHHHH',
      'DDBBBHHH',
      'DDBCEEEE',
      'DBBCFFGG',
      'ABCCFFGG',
      'AACCCFFG',
      'AACCCFFG',
      'AACCCCFG')),
    ('HUGE', 10, 2,
     ('BBBBBJJJJJ',
      'BCBCBBJJJG',
      'DCCCJJJHHG',
      'DCDCJJHHHG',
      'DDDJJJJHEE',
      'DDJJIIIEEE',
      'ADDDFIIIEE',
      'AAFFFFFIEE',
      'AAAFFIIIEE',
      'AAFFFIIIIE')),
    ('HUGE', 10, 2,
     ('FFFHHHEEEE',
      'FFHHHIIIII',
      'FFFHHIIIAI',
      'FFFIIIBIAA',
      'FFIIIIBBAA',
      'FJIICBBBAA',
      'JJJDCCGGAA',
      'JJJDCCGGGG',
      'JJDDGGGGGG',
      'JJJDGGGGGG')),
    ('HUGE', 10, 2,
     ('ACCCIIIIJJ',
      'ACCJIIJIIJ',
      'ACCJJJJJJJ',
      'CCJJJDJJJJ',
      'CCJJHDDFFF',
      'GGGJHDBBFF',
      'GGGHHBBFFF',
      'GGGHHHBBBB',
      'GGHHHHBBBB',
      'HHHHHEEEEE')),
    ('HUGE', 10, 2,
     ('CCCEEEEEEJ',
      'CCCEEEEBJJ',
      'CCDJJJBBBJ',
      'CCDJJJJJJJ',
      'CDDJIIJHHH',
      'JDJJIIJFHH',
      'JJJJIFFFHH',
      'JAAAIIFGGG',
      'JJJJIIGGGG',
      'JJJJIIGGGG')),
    ('HUGE', 10, 2,
     ('JJJEEEEDDD',
      'JJJJJIIDDD',
      'JJCCIIIDDD',
      'FJCCIIIDDG',
      'FJCCIIHHGG',
      'FJJIIIIHGG',
      'JJJAAAAHGG',
      'JJJBBHHHHG',
      'JJBBBGGHHG',
      'JJBBBGGGGG')),
    ('HUGE', 10, 2,
     ('BBBBAIIFFF',
      'BBBAAIFFFF',
      'BBAAAIIFFG',
      'AAAAIIIIGG',
      'JAAHHIIGGG',
      'JHHHHEEEGG',
      'JHHHEEDDDG',
      'JHHHCCDGGG',
      'HHHHCDDDGG',
      'HHHHCDDDGG')),
)
